### ISSUE TITLE
Folder Colors

### ISSUE THREAD

**Issue by reya276** [gusbemacbe/suru-plus-dark#3]
Ugh....How can I change the folder color to Blue instead of this ugly orange. Hell I'll take purple over this.

**Comment by gusbemacbe** [comment]
Hi @reya276 !

As I have already said in another repository that you can use [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders), but it does not support Suru++ Dark, because Suru++ Dark is outdated and buggy. Therefore, I will focus on finishing the Suru++ 20, then will merge the new verison of Suru++ 20 into Suru++ Asprómauros and into Suru++ Dark to upgrade them, and also into Suru++ Telinkrin to re-telinkrinise everything and redesign the Suru++ Arrogin.

**Comment by gusbemacbe** [comment]
Hello @reya276 !

As I have finished Suru++ 25, I have just upgraded Suru++ Dark, renaming it to Suru++ 25 Dark. It won new folders colour fitting with dark environments (you can see the list of folders colours in the README). Both Suru++ 25 and Suru++ 25 Dark also are officially compatible with Oomox, the which allows you to change the colour of all 16px icons and of all folders with any colour you want.
